# Generated by Django 3.2.4 on 2021-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_motricidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rincon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
